simulation:
  dt: 0.02
  target_tolerance: 0.3

domain:
  xmin: 0.0
  xmax: 20.0
  ymin: 0.0
  ymax: 4.0

agent:
  radius: 0.25
  desired_speed: 1.3
  max_speed: 1.5
  perception_radius: 2.5
  social_radius: 0.75
  speed_A: 1.15

forces:
  gradient:
    strength: 20.0
  repulsive:
    strength: 50.0 
    decay: 10.0
  resistance:
    gamma: 2.0
  random:
    probability: 0.1
    strength: 2.0

spawn:
  rate: 1.0
  max_agents: 500
  min_dist: 0.6
  left:
    x: 0.5
    y_range: [0.5, 3.5]
    target: [19.5, 2.0]
  right:
    x: 19.5
    y_range: [0.5, 3.5]
    target: [0.5, 2.0]

walls:
  - type: horizontal
    y: 0.0
    normal: [0, 1]
  - type: horizontal
    y: 4.0
    normal: [0, -1]
  - type: vertical
    x: 10.0
    normal: [-1, 0]
    y_range: [0.0, 1.5]
  - type: vertical
    x: 10.0
    normal: [1, 0]
    y_range: [0.0, 1.5]
  - type: vertical
    x: 10.0
    normal: [-1, 0]
    y_range: [2.5, 4.0]
  - type: vertical
    x: 10.0
    normal: [1, 0]
    y_range: [2.5, 4.0]
